# Generated by Django 5.2 on 2025-06-28 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_alter_accesscode_team_accesscode_one_code_per_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='teammembership',
            name='one_team_per_user',
            constraint=models.UniqueConstraint(fields=('user',), name='one_team_per_user', violation_error_message='A user can be part of only one team at a time-unique constraint of teammembership.'),
        ),
        migrations.AlterConstraint(
            model_name='teammembership',
            name='one_leader_per_team',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'leader')), fields=('team',), name='one_leader_per_team', violation_error_message='A team can have only 1 leader-unique constraint of teammembership.'),
        ),
    ]
