# Generated by Django 5.2 on 2025-06-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_alter_teammembership_one_team_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='masked_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
