# Generated by Django 5.2 on 2025-07-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fts_app', '0008_file_access_code_folder_access_code'),
        ('permissions', '0007_accesscode_masked_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='working_files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='fts_app.file'),
        ),
    ]
