# Generated by Django 5.2 on 2025-07-23 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_team_working_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='permissions.team'),
        ),
    ]
