
# error_log /var/log/nginx/error.log;

upstream fts_django {
    server django-web:8000; #service name is django-web in compose file
}

server {
    listen       80;
    # server_name  localhost;
    root   /usr/share/nginx/html;
    access_log /var/log/nginx/access.log;

    location / {   #serve frontend here
        try_files $uri /index.html;
    }
    location /admin/ {
        proxy_pass http://fts_django/admin/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;  #this is very important as it adds the path apiv1 to all the serialiser hyperlinks
        proxy_redirect off;
    }

    location /apiv1/ {  #backend here
    #     if ($request_method = 'OPTIONS') {
    #     add_header 'Access-Control-Allow-Origin' '*' always;
    #     add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
    #     add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-CSRFToken' always;
    #     add_header 'Access-Control-Allow-Credentials' 'true' always;
    #     return 204;
    # }
        proxy_pass http://fts_django/apiv1/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;   
        proxy_redirect off;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

}