# https://saasitive.com/tutorial/django-celery-redis-postgres-docker-compose/
# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
# Stage 1: Base build stage
FROM python:3.13-slim AS builder
 
# Create the app directory
RUN mkdir /app
RUN mkdir app/staticfiles
# Set the working directory
WORKDIR /app
 
# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
 
# Upgrade pip and install dependencies
RUN pip install --upgrade pip 
# Install dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    netcat-openbsd

# Copy the requirements file first (better caching)
COPY requirements.txt /app/
 
# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt
 
# Stage 2: Production stage
FROM python:3.13-slim

RUN pip install --upgrade pip 
# Install dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    netcat-openbsd
 
RUN useradd -m -r appuser && \
   mkdir /app && \
   mkdir app/staticfiles &&\
   chown -R appuser /app


 
# Copy the Python dependencies from the builder stage
COPY --from=builder /usr/local/lib/python3.13/site-packages/ /usr/local/lib/python3.13/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
 
# Set the working directory
WORKDIR /app


# copy entrypoints
COPY entrypoint.sh .
COPY worker-entrypoint.sh .

RUN sed -i 's/\r$//g' entrypoint.sh
RUN sed -i 's/\r$//g' worker-entrypoint.sh

RUN chmod +x entrypoint.sh
RUN chmod +x worker-entrypoint.sh
 
# Copy application code
# COPY --chown=appuser:appuser . .
 
# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
 
# Switch to non-root user
USER appuser
 
# Expose the application port
EXPOSE 8000 
 

# run entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
# we put them in compose instead


# Start the application using Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "ftssite.wsgi:application"]