"""
Django settings for ftssite project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=0))

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fts_app',
    'accounts',
    'permissions',
    # for django guardian
    'rest_framework',
    'rest_framework_simplejwt',
    'guardian',
    "debug_toolbar",

    # for cors api calls
    'corsheaders',

    'django_celery_beat',

    'storages'
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend', # we got this for django guardian
)

ANONYMOUS_USER_NAME =None # this is for django guardian, disables creation by anonymous users

AUTH_USER_MODEL = 'accounts.Myuser'

# https://medium.com/django-unleashed/securing-django-rest-apis-with-jwt-authentication-using-simple-jwt-a-step-by-step-guide-28efa84666fe
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        # 'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # now since we customised the JWTAuthentication in accounts,authenticate.py we will plug it here
        'accounts.authenticate.CustomAuthentication',
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',

        # from the book REST api with django
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
    ),
}

SIMPLE_JWT = {
    # custom token serialiser in serliase.py
    # https://medium.com/@cassymyo/how-to-get-token-user-information-using-simple-jwt-django-rest-framework-and-react-js-part-1-af528bab854a
    "TOKEN_OBTAIN_SERIALIZER": "accounts.serialiser.MyTokenObtainPairSerializer",
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=240),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME': timedelta(days=30),
    'SLIDING_TOKEN_REFRESH_LIFETIME_LATE_USER': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME_LATE_USER': timedelta(days=30),
}


MIDDLEWARE = [
    # for cors api calls
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # this was added
    # 'fts_app.middleware.jwt_token_retrieve.CustomTokenMiddleware',
    # -----x------
      # jwt refresh token                 
    # "fts_app.middleware.refresh_token.RefreshJWTMiddleware",

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'ftssite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ftssite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

ONLINE_DB = False
# if ONLINE_DB:
#     DATABASES = {
#   'default': {
#     'ENGINE': 'django.db.backends.postgresql',
#     'NAME': os.getenv('PGDATABASE'),
#     'USER': os.getenv('PGUSER'),
#     'PASSWORD': os.getenv('PGPASSWORD'),
#     'HOST': os.getenv('PGHOST'),
#     'PORT': os.getenv('PGPORT', 5432),
#     'OPTIONS': {
#       'sslmode': 'require',
#     },
#     'DISABLE_SERVER_SIDE_CURSORS': True,
#   }
# }
# elif DEBUG == False:
#     DATABASES = {
#     "default": {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DATABASE_NAME', 'fts1'),
#         'USER': os.getenv('DATABASE_USERNAME', 'postgres'),
#         'PASSWORD': os.getenv('DATABASE_PASSWORD', 'black'),
#         'HOST': os.getenv('DATABASE_HOST', 'localhost'),
#         'PORT': os.getenv('DATABASE_PORT', 5432),
#     }
# }
# else: 
#     DATABASES = {
#     "default": {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME':  'fts1',
#         'USER':  'postgres',
#         'PASSWORD':  'black',
#         'HOST': 'localhost',
#         'PORT':  5432,
#     }
# }
# import os

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':  'fts1',
        'USER':  'postgres',
        'PASSWORD':  'black',
        'HOST': 'localhost',
        'PORT':  5432,
    }
}


# DATABASES = {
#     "default": {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DATABASE_NAME', 'fts1'),
#         'USER': os.getenv('DATABASE_USERNAME', 'postgres'),
#         'PASSWORD': os.getenv('DATABASE_PASSWORD', 'black'),
#         'HOST': os.getenv('DATABASE_HOST', 'localhost'),
#         'PORT': os.getenv('DATABASE_PORT', 5432),
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT =  os.path.join(BASE_DIR, 'staticfiles')
# for collectstatic

USE_SPACES = True
if USE_SPACES:
    # settings
    AWS_ACCESS_KEY_ID = os.getenv('DO_bucket_access_key_id')
    AWS_SECRET_ACCESS_KEY = os.getenv('DO_SECRET_ACCESS_KEY')

    AWS_STORAGE_BUCKET_NAME = os.getenv('DO_AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('DO_AWS_S3_ENDPOINT_URL')
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_DEFAULT_ACL = 'public-read'

    PUBLIC_MEDIA_LOCATION = 'crumpet'

    # Use CDN for serving media
    MEDIA_URL = os.getenv('DO_BUCKET_CDN_ENDPOINT') + '/crumpet/'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# https://django-debug-toolbar.readthedocs.io/en/latest/installation.html
# these settings will change during production
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
    '139.59.60.118:1337',
    '139.59.60.118'

]

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.history.HistoryPanel',
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.alerts.AlertsPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Use the appropriate Redis server URL
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


# CROSS ORIGIN RESOURCE SHARING (CORS) for connecting to frontend
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:1337",

    'http://139.59.60.118:1337',
    'http://139.59.60.118',
    'https://139.59.60.118:1337',
    'https://139.59.60.118',

    'http://www.crumpet.cc',
    'http://crumpet.cc',
    'https://www.crumpet.cc',
    'https://crumpet.cc',
    
]
# CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://localhost:1337",

    'http://139.59.60.118:1337',
    'http://139.59.60.118',
    'https://139.59.60.118:1337',
    'https://139.59.60.118',

    'http://www.crumpet.cc',
    'http://crumpet.cc',
    'https://www.crumpet.cc',
    'https://crumpet.cc',
]


CORS_ALLOW_HEADERS = [
'accept',
'accept-encoding',
'authorization',
'content-type',
'dnt',
'origin',
'user-agent',
'x-csrftoken',
'x-requested-with',
]

# CORS_ALLOW_ALL_ORIGINS=True


CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

STORAGES = {
    "default": {
        "BACKEND": 'ftssite.storage_backends.PublicMediaStorage',
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

BROKER_URL = os.getenv('REDIS', 'redis://redis:6379/0')

print("[DEBUG] AWS_S3_ENDPOINT_URL =", AWS_S3_ENDPOINT_URL)
print("[DEBUG] MEDIA_URL =", MEDIA_URL)
print("Connecting to DB:", os.getenv("DATABASE_HOST"), os.getenv("DATABASE_NAME"), os.getenv("DATABASE_USERNAME"))